services:
    db:
        image: postgres:16.3
        container_name: postgres-mydramalist
        environment:
            POSTGRES_DB: dramalist
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: adminpassword
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    redis:
        image: redis:latest
        container_name: redis-mydramalist
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data #persistent storage for Redis data
        command: ["redis-server", "--appendonly", "yes"]
volumes:
    db-data:
    redis_data:
